'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects

Namespace EFDataSourceSnippets

    Public Partial Class NorthwindEntities
        Inherits DbContext

        Public Sub New()
            MyBase.New("name=NorthwindEntities")
        End Sub

        Protected Overrides Sub OnModelCreating(ByVal modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub

        Public Overridable Property Categories As DbSet(Of Category)

        Public Overridable Function CustOrderHist(ByVal customerID As String) As ObjectResult(Of CustOrderHist_Result)
            Dim customerIDParameter = If(Not Equals(customerID, Nothing), New ObjectParameter("CustomerID", customerID), New ObjectParameter("CustomerID", GetType(String)))
            Return CType(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CustOrderHist_Result)("CustOrderHist", customerIDParameter)
        End Function
    End Class
End Namespace
